"""Walks downloaded datasets, prints stats, writes preprocess-data/README.md."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent
IMG_EXT = {".jpg", ".jpeg", ".png"}


def stat_casia() -> dict:
    base = ROOT / "casia-webface"
    # CASIA layout: casia-webface/<identity_id>/*.jpg (after unzip).
    # Find the directory of identities; some Kaggle dumps nest one level deeper.
    candidates = [base, *(p for p in base.iterdir() if p.is_dir())]
    for c in candidates:
        ids = [d for d in c.iterdir() if d.is_dir()]
        if len(ids) > 100:
            counts = Counter()
            for d in ids:
                counts[d.name] = sum(1 for f in d.iterdir() if f.suffix.lower() in IMG_EXT)
            return {
                "root": str(c.relative_to(ROOT)),
                "identities": len(counts),
                "images": sum(counts.values()),
                "min_per_id": min(counts.values()),
                "max_per_id": max(counts.values()),
                "median_per_id": sorted(counts.values())[len(counts) // 2],
            }
    return {"error": "CASIA layout not recognized"}


def stat_celeba() -> dict:
    base = ROOT / "celeba"
    identity_file = next(base.rglob("identity_CelebA.txt"), None)
    img_dir = next(base.rglob("img_align_celeba"), None)
    if identity_file is None or img_dir is None:
        return {"error": "CelebA missing identity_CelebA.txt or img_align_celeba/"}
    counts = Counter()
    with identity_file.open() as f:
        for line in f:
            _, ident = line.strip().split()
            counts[ident] += 1
    n_imgs = sum(1 for f in img_dir.iterdir() if f.suffix.lower() in IMG_EXT)
    return {
        "identity_file": str(identity_file.relative_to(ROOT)),
        "img_dir": str(img_dir.relative_to(ROOT)),
        "identities": len(counts),
        "images_labeled": sum(counts.values()),
        "images_on_disk": n_imgs,
        "min_per_id": min(counts.values()),
        "max_per_id": max(counts.values()),
    }


def stat_lfw() -> dict:
    base = ROOT / "lfw"
    pairs = next(base.rglob("pairs.txt"), None)
    deep = next(base.rglob("lfw-deepfunneled"), None) or next(base.rglob("lfw_funneled"), None)
    if pairs is None or deep is None:
        return {"error": "LFW missing pairs.txt or lfw-deepfunneled/"}
    pairs_lines = pairs.read_text().splitlines()
    return {
        "pairs_file": str(pairs.relative_to(ROOT)),
        "img_root": str(deep.relative_to(ROOT)),
        "pairs_count": len(pairs_lines) - 1,  # first line is fold/count header
        "identities_on_disk": sum(1 for d in deep.iterdir() if d.is_dir()),
    }


def main() -> None:
    report = {
        "casia": stat_casia(),
        "celeba": stat_celeba(),
        "lfw": stat_lfw(),
    }
    print(json.dumps(report, indent=2))
    readme = ROOT / "README.md"
    readme.write_text(
        "# Datasets\n\nAuto-generated by `check.py`.\n\n"
        "```json\n" + json.dumps(report, indent=2) + "\n```\n"
        "\nRaw data is **gitignored**; run `infra/setup_vm.sh` to recreate.\n"
    )


if __name__ == "__main__":
    main()
